### ISSUE TITLE
ImportError: libcblas.so.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by on8pz** [projecthorus/chasemapper#47]
Looks like the latest docker image does not start. It shows the following error and keeps restarting:

```
Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/root/.local/lib/python3.9/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/root/.local/lib/python3.9/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libcblas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/chasemapper/horusmapper.py", line 30, in <module>
    from chasemapper.geometry import *
  File "/opt/chasemapper/chasemapper/geometry.py", line 10, in <module>
    import numpy as np
  File "/root/.local/lib/python3.9/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/root/.local/lib/python3.9/site-packages/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/usr/local/bin/python3"
  * The NumPy version is: "1.23.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libcblas.so.3: cannot open shared object file: No such file or directory
```

```
hans@DebHans:/data/chasemapper$ docker pull ghcr.io/projecthorus/chasemapper:latest
latest: Pulling from projecthorus/chasemapper
Digest: sha256:22bfb103c98180fdc91a31bc97a3577564370a1ce7065bbf54c59e951bb9a1f0
Status: Image is up to date for ghcr.io/projecthorus/chasemapper:latest
ghcr.io/projecthorus/chasemapper:latest
```

**Comment by darksidelemm** [comment]
Which platform are you using?

There are unfortunately some known issues with the docker containers on
some platforms at the moment. I believe @snh was looking into it.

**Comment by on8pz** [comment]
```
hans@DebHans:/data/chasemapper$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```

**Comment by darksidelemm** [comment]
Sorry I should have said what architecture. E.g. x64, arm of some kind, etc.

The amd64 build is definitely broken.

**Comment by on8pz** [comment]
```
hans@DebHans:/data/chasemapper$ uname -a
Linux DebHans 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux

```

I guess I'm out of luck then ?

**Comment by darksidelemm** [comment]
Until it gets fixed :-) 

You can also do a 'native' install, which is a bit more involved: https://github.com/projecthorus/chasemapper#local-install---dependencies

**Comment by on8pz** [comment]
FYI, all it took to fix was a
`apt-get install libatlas-base-dev`
in the docker image
